export const BIZ_MENU_COLUMNS = [
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'id',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.id',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'name',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.name',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'description',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.description',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'countryCode',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.countryCode',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'brn',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.brn',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'address',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.address',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'bizplaces',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.bizplaces',
    gridWidth: 0
  },
  {
    nullable: false,
    sortRank: 0,
    gridRank: 0,
    virtualField: false,
    colSize: 64,
    reverseSort: false,
    uniqRank: 0,
    searchRank: 0,
    ignoreOnSave: false,
    colType: 'string',
    name: 'state',
    menuName: 'Company',
    rank: 10,
    extField: false,
    term: 'label.state',
    gridWidth: 0
  }
]
